services:
    database:
        image: mysql:8.4.0
        restart: always
        container_name: database
        environment:
            MYSQL_DATABASE: 'user_mng_sys'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'user1221'
            MYSQL_ROOT_PASSWORD: 'user3343'
        ports:
            - "3306:3306"
        volumes:
            - starter_kit_db:/var/lib/mysql
        networks:
            - app_net
networks:
    app_net:
        driver: bridge
volumes:
    starter_kit_db:



